//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarksmanshipTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public long Id { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
    }
}
