//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarksmanshipTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionParticipant
    {
        public long Id { get; set; }
        public long SessionId { get; set; }
        public long PersonId { get; set; }
        public Nullable<long> Minutes { get; set; }
        public Nullable<decimal> Credits { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Session Session { get; set; }
    }
}
