//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarksmanshipTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrackingDataEntities : DbContext
    {
        public TrackingDataEntities()
            : base("name=TrackingDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PeopleAward> PeopleAwards { get; set; }
        public virtual DbSet<Rank> Ranks { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionParticipant> SessionParticipants { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
    }
}
